name: "NeoBrutalism CI"

on: 
  push:
    branches: 
      - main
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

# Refer https://github.com/Alamofire/Alamofire/blob/master/.github/workflows/ci.yml
jobs:
  iOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=18.0,name=iPhone 16"
            name: "iOS 18.0"
            testPlan: "iOS"
            xcode: "Xcode_16.0"
            runsOn: macOS-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Disable macro validation
        run: |
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      
      - name: Run tests and save result bundle
        run: |
          mkdir -p test_output
          set -o pipefail
          env NSUnbufferedIO=YES xcodebuild \
            -scheme "NeoBrutalism" \
            -destination "${{ matrix.destination }}" \
            -resultBundlePath "test_output/${{ matrix.name }}.xcresult" \
            -enableCodeCoverage YES \
            -parallel-testing-enabled YES \
            CODE_SIGNING_ALLOWED=NO \
            clean test 2>&1 | xcbeautify --renderer github-actions
